# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4608M
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.conventions.runs.create-default-run-per-type=false

## Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1.0.0-alpha,)
neo_version=26.1.0.0-alpha.15+pre-3
neo_version_range=[26.1.0.0-alpha,)
loader_version_range=[4,)

## Mod Properties
mod_id=modpackutils
mod_name=Modpack Utils
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.benbenlaw.modpackutils
mod_authors=benbenlaw
mod_description=Useful modpack utilities including tags for portal and other things.

jei_mc_version=26.1-pre-3
jei_version=29.1.0.16

## Auto Updates
release_type=release
release_versions = 26.1
curseforge_id = 1135181
modrinth_id = tfpHINm8
changelog=Join the discord here for mod and modpack updates and support https://discord.gg/benbenlaw \
  https://github.com/benbenlaw/BBLCore/blob/master/changelog